language: node_js
node_js:
- '0.12'
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: MNsW8Lg1YIhm8V0YqzuzV+Uwllg6TFWllfAnSzbllonFRMJpwM1g3aO9GLlP2WcbmbLBWk0BolYa2o7DQSUxcq/Vvv4RWZTdrSLnNRHKczbI8PhQRy+/NyOqOSXAZ2ZVVYDKTnq3DYZsWl3sUnML+iClkAUSDnH8dxUyPnoTkcYE4t1HqLhOg1dkAtIUolJ7sIXdjeHadzWhFQsn+qVxyXgcw0NwmpIo9zQlHwwLvIjMpL+Z3CfPHaNWyZ0WpshFZSDjFJ+39BOAYSoTm3HQS2ZYVk4c1B/Ss3jaJS+BPT2gnsKeNnX+URFMDz7R7GDOEq85cBZuSwdZif6YtsoSfyB44/3o33Bl7svZ7TAoaZbRRMndj/DQ+qZLdoOuLc1D4nPrN8bsIiX0BOD8gxZas53IOgCFTo2csUJV5HpOFhBu8WEFVJn7Lf+LxQtZBtmLEUN0NpG5Rp47lnc6pg09wIi6LMEEHY1st1RFctAibIEjpMtfqWamONWXOsuLOBT96BAroeTqAsHDceWafQUeWPqaBWT5RfCPw974todrhoPPSwIp+00I0n/r73LjHT0ddXvHn52zmY9KWHN8Jeleoj942n1DNNzy4yUHUVJH4EjMKFg+AU2FWzQMHSDEmspOakohvLaPZquJxhqnZkxpcwydJbbNjWcFSOVCJJgk+5E=
  on:
    branch: master
    repo: plepers/nanogl-mouse
