language: node_js
node_js:
- '0.12'
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: n4mQk7nRKECkUBVI8bqq6c1Pr2ugX6BjWQnrtUK5n91O+j9JZWqJ0jWsUKoq6t82YcLMEnBpJ0DYLrPKoqChxkNlNVaTXxAFeoN7z8u3PA3rvkCKil2fkdy09r2s9KeI0rD2kEsNNBlLGLznr7/c0ytc3k0TvcBj8gDNNS/ZOD8wniyZntmKiawZsJwXDn8menaM+CMUqNOPGj3CUozgSolFOnEue5o2lSO/vfUS37QSi4SQr9tklLGZ4m+MB5JlagfZvr9DGui+EcVwthjj802P943UlU5PE4ZytceYuWzLtKTw7hop++t6fmw/rYkSSxJ6Yt4EEFPI6/7mczxJzz8UpjNV3oJ4v9omtwbSRQKh9MU9NB6VkWGJe3vsH5mDSibaUlzk6Gc0eRjyo690e5bdA75segx4VYVPjlJCIA1oUIhwNrEW36jgNQtjj/IayiakoHFQZBD0E0YWQfSOB5EDS9KH2QtpHFmE/POfTBHcymJoURz50yXVWPVv6igcDHqCuDHiDidTivYGQKoe94mTjzc8b+vq28AgXekSissLCYr/gZSKPL2RyWBPGwTRmk7VcQ99s+X3rUUHLAAY5st6JqMNqu9rgsgJX0d1N40lrOCLm7fsHSGwxnPpspiqmcNoxBYeZhApUeEpmvt4nXzmuTV24uDyPFfKKh9qk98=
  on:
    branch: master
    repo: plepers/nanogl-mouse